In [ ]:
import pandas as pd # create data

df = pd.DataFrame({
    "id":[1,2,2,4],
    "name":["Amit",None,"Riya","John"],
    "sales":[200,-50,300,None]
})

df

   id  name  sales
0   1  Amit  200.0
1   2  None  -50.0
2   2  Riya  300.0
3   4  John    NaN

In [ ]:
df.isnull().sum()  #null check

id       0
name     1
sales    1
dtype: int64

In [ ]:
df.duplicated() # duplicate check

0    False
1    False
2    False
3    False
dtype: bool

In [ ]:
df[df["sales"]<0] #range check

   id  name  sales
1   2  None  -50.0

In [ ]:
df["name"].fillna("Unknown", inplace=True) fix datas [it should be an error]

SyntaxError: invalid syntax (2495588582.py, line 1)

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
df["sales"] = df["sales"].apply(lambda x: abs(x) if x < 0 else x)